name: Update Kustomize with new version
description: Updates image tag in Kustomize and commits

inputs:
  overlay-path:
    required: true
  new-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install yq
      shell: bash
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

    - name: Update image tag
      shell: bash
      run: |
        yq e -i '.images[0].newTag = env(NEW_VERSION)' "${{ inputs.overlay-path }}"

    - name: Commit and push changes
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        FILES_TO_COMMIT="${{ inputs.overlay-path }}"

        # Python project
        if [ -f "pyproject.toml" ]; then
          FILES_TO_COMMIT="$FILES_TO_COMMIT pyproject.toml"
        fi

        # React project
        if [ -f "src/package.json" ]; then
          FILES_TO_COMMIT="$FILES_TO_COMMIT src/package.json"
        fi

        git add $FILES_TO_COMMIT
        git commit -m "[skip ci] Release version $NEW_VERSION" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref }}