name: Build React App
description: Runs pnpm build with injected Vite env vars

runs:
  using: composite
  steps:
    - name: Build React
      working-directory: src
      shell: bash
      run: |
        pnpm build