name: Run Pytest
description: Executes Django tests via pytest

runs:
  using: "composite"
  steps:
    - name: Run pytest
      shell: bash
      run: |
        if [ -d "src" ]; then
          echo "→ Running pytest on src/"
          poetry run pytest src/ --maxfail=3 --disable-warnings -q
        else
          echo "→ No src directory found, running pytest on project root"
          poetry run pytest . --maxfail=3 --disable-warnings -q
        fi