name: Run Pytest
description: Executes Django tests via pytest

runs:
  using: "composite"
  steps:
    - name: Run pytest
      shell: bash
      run: |
        if [ -d "src" ]; then
          echo "→ Running pytest on src/ (excluding integration tests)"
          poetry run pytest src/ -m "not integration" --maxfail=3 --disable-warnings -q
        else
          echo "→ No src directory found, running pytest on project root (excluding integration tests)"
          poetry run pytest . -m "not integration" --maxfail=3 --disable-warnings -q
        fi