name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish-and-notify:
    runs-on: ubuntu-latest

    steps:
      # Send Slack notification
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: ":construction_worker: *ci/cd* updated!"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: |
                    :construction_worker: The configuration of *CI/CD pipelines* has been updated!
                    *Commit Message:* ${{ github.event.head_commit.message }}

                    *Repository:* ${{ github.repository }}
                    *Pushed by:* ${{ github.actor }}